server:
  port: 8094
spring:
  application:
    name: merger
  redis:
    host: 121.40.64.224
    port: 6379
    max-idle: 8
    min-idle: 0
    max-active: 8
    maxwait: -1
    timeout: 5000
    isRedisCache: 1  #是否使用redis缓存
    password: Yin123456.
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000 #熔断超时 5s
          strategy: SEMAPHORE
#生成的表数据 后续可以考虑读取配置文件
ly:
  jdbc:
    username: ybx
    password: Yin123456.
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.64.224:3306/data_merge?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
  pay:
    appID: wx8397f8696b538317
    mchID: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectTimeoutMs: 1000
    httpReadTimeoutMs: 5000
    notifyUrl: http://localhost:10010/api/merger/pay/payNotifyUrl #公网地址 或者内网穿透