server:
  port: 10010
spring:
  application:
    name: api-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    max-idle: 8
    min-idle: 0
    max-active: 8
    maxwait: -1
    timeout: 0
    isRedisCache: 1  #是否使用redis缓存
    password: Yin123456.
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  add-host-header: true
  prefix: /api # 路由路径前缀 路由拿来转发的 需要被访问到的话需要在这个里面加
  routes:
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    shiro: /shiro/**
    user: /user/**
    permission: /permission/**
    merger: /merger/**
  sensitive-headers:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000 #熔断超时 5s
          strategy: SEMAPHORE
ribbon:
  ConnectTimeout: 50000 #ribbon连接超时时间
  ReadTimeout: 25000 #ribbon读取超时时长
  MaxAutoRetries: 0 #当前服务器重试次数
  MaxAutoRetriesNextServer: 0  #切换服务重试次数
