spring:
  application:
    name: shiro
  redis:
    host: 121.40.64.224
    port: 6379
    max-idle: 8
    min-idle: 0
    max-active: 8
    maxwait: -1
    timeout: 5000
    isRedisCache: 1  #是否使用redis缓存
    password: Yin123456.
server:
  port: 8092
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000 #熔断超时 5s
          strategy: SEMAPHORE
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

