server:
  port: 8090
spring:
  application:
    name: user
  redis:
    host: 121.40.64.224
    port: 6379
    max-idle: 8
    min-idle: 0
    max-active: 8
    maxwait: -1
    timeout: 5000
    isRedisCache: 1  #是否使用redis缓存
    password: Yin123456.
  rabbitmq:
    host: 106.54.117.228
    virtual-host: /leyou
    username: ybx
    password: Yin123456.

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

ly:
  smtp:
    user: 917367646@qq.com
    author: rbperssvoczlbcdi