server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000 #熔断超时 5s
          strategy: SEMAPHORE
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image: #可做头像
    width: 60 #缩略图
    height: 60
  tracker-list: # tracker地址
    - 121.40.64.224:22122

ly:
  upload:
    baseUrl: http://121.40.64.224:18080/  #可以添加期望nginx代理转发到地址和端口
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp
      - image/jpg