FROM mcr.microsoft.com/java/jre:8u212-zulu-alpine

MAINTAINER ybx <917367646@qq.com>


EXPOSE 8092

ADD target/leyou-shiro-1.0.0-SNAPSHOT.jar leyou-shiro-1.0.0-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","leyou-shiro-1.0.0-SNAPSHOT.jar"]
