server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://47.96.144.36/ybx
    username: root
    password: Yin123456.
  rabbitmq:
    host: 192.168.10.199
    username: ybx
    password: Yin123456.
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: leyou.item.exchange
    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl